# YAML pipeline to run JavaScript file in Azure DevOps

trigger:
  branches:
    include:
      - master
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    # Print current directory for debugging (optional)
    pwd
    
    # Run the JavaScript file using Node.js (replace with your file name)
    node path/to/your/javascript/file.js
  displayName: 'Run JavaScript file'
